#!/bin/zsh
#
# Rust configuration for zsh
# This file contains all Rust-related configurations
#

# Rust environment variables
export RUSTUP_HOME="$HOME/.rustup"
export CARGO_HOME="$HOME/.cargo"
export PATH="$CARGO_HOME/bin:$PATH"

# Rust aliases
alias rustc-version="rustc --version"
alias cargo-version="cargo --version"
alias rustup-version="rustup --version"
alias cargo-update="cargo install-update -a"
alias cargo-clean="cargo clean"
alias cargo-doc="cargo doc --open"
alias cargo-audit="cargo audit"
alias cargo-outdated="cargo outdated"

# Rust project creation function
new-rust() {
    if [ $# -lt 1 ]; then
        echo "Usage: new-rust <project-name> [--lib]"
        return 1
    fi
    
    local project_name=$1
    local project_type="--bin"
    
    if [[ "$2" == "--lib" ]]; then
        project_type="--lib"
    fi
    
    # Create new Rust project
    cargo new "$project_name" $project_type
    
    # Navigate to project directory
    cd "$project_name" || return
    
    # Add useful dependencies to Cargo.toml
    cat >> Cargo.toml << EOF

# Development dependencies
[dev-dependencies]
criterion = "0.5"  # Benchmarking
pretty_assertions = "1.4"  # Better test assertions

# Common dependencies (uncomment as needed)
# serde = { version = "1.0", features = ["derive"] }
# serde_json = "1.0"
# tokio = { version = "1.36", features = ["full"] }
# clap = { version = "4.5", features = ["derive"] }
# anyhow = "1.0"
# thiserror = "1.0"
# log = "0.4"
# env_logger = "0.11"
EOF
    
    # Create .gitignore
    cat > .gitignore << EOF
# Generated by Cargo
/target/
Cargo.lock

# These are backup files generated by rustfmt
**/*.rs.bk

# IDE files
.idea/
.vscode/
*.iml

# macOS files
.DS_Store
EOF
    
    # Initialize git repository if git is available
    if command -v git >/dev/null 2>&1; then
        git init
        git add .
        git commit -m "Initial commit"
    fi
    
    echo "Rust project '$project_name' created successfully!"
}
